name: InfrastructureDependencyManager CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-13
    steps:
      - name: Check out
        uses: actions/checkout@v4
        
      - name: Use Xcode 15.1
        run: sudo xcode-select --switch /Applications/Xcode_15.1.app

      - name: Build
        run: |
          swift build
          
      - name: Test
        run: |
          swift test
